<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CATALOGO MUSICAL</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet">
  <link rel="stylesheet" href="<?= BASE_URL ?>assets/style.css">
</head>
<body>

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark violet">
    <div class="container">
      <a class="navbar-brand" href="<?= BASE_URL ?>home">
         <img src="<?=BASE_URL?>assets/img/logoCatalogoMusical.png" alt="logo"
         class="logo-navbar">
      </a>
      <div class="navbar-nav me-auto">
        <a class="nav-link active" href="<?= BASE_URL ?>home">Artistas</a>
         <a class="nav-link active" href="<?= BASE_URL ?>album">Albumes</a>
      </div>
      <div class="navbar-nav">

    <?php if (isset($this->user) && $this->user) { ?>

        <span class="navbar-text me-3">
            <i class="bi bi-person-circle"></i>
            <?= $this->user->email ?>
        </span>

        <a class="nav-link" href="<?= BASE_URL ?>adminArtistas">
            Admin Artistas
        </a>

        <a class="nav-link" href="<?= BASE_URL ?>adminAlbumes">
            Admin Álbumes
        </a>

        <a class="nav-link" href="<?= BASE_URL ?>logout">
            <i class="bi bi-box-arrow-right"></i>
            Cerrar Sesion
        </a>

    <?php } else { ?>

        <a class="nav-link" href="<?= BASE_URL ?>login_form">
            <i class="bi bi-box-arrow-in-right"></i>
            Iniciar Sesion
        </a>

    <?php } ?>

</div>
      </div>
    </div>
  </nav>
