<?php require_once __DIR__ . '/layout/header.phtml'; ?>
<div class="container my-5">

    <div class="row justify-content-center">

        <div class="col-md-6">

            <div class="card shadow">

                <div class="card-body">

                    <h2 class="text-center mb-4">Iniciar sesión</h2>

                    <form action="<?= BASE_URL ?>login" method="POST">

                        <div class="mb-3">
                            <label class="form-label">
                                Usuario
                            </label>

                            <input type="text"
                                   name="email"
                                   class="form-control"
                                   required>
                        </div>

                        <div class="mb-3">
                            <label class="form-label">
                                Contraseña
                            </label>

                            <input type="password"
                                   name="password"
                                   class="form-control"
                                   required>
                        </div>

                        <button type="submit"
                                class="btn w-100 violet">
                            Ingresar
                        </button>

                    </form>

                </div>

            </div>

        </div>

    </div>

</div>

<?php require_once __DIR__ . '/layout/footer.phtml'; ?>